version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/nginx-vod-filo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t thething/nginx-vod-filo:build_${CIRCLE_BUILD_NUM} -t thething/nginx-vod-filo:${CIRCLE_SHA1} -t thething/nginx-vod-filo:latest .
      - run:
          name: Push to docker
          command: |
            docker login quay.io -u $QUAY_USER -p $QUAY_PASS
            docker push thething/nginx-vod-filo
      - deploy:
          name: Deploy to production
          command: |
            echo Not implemented
workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: org-global
